Added Intake Command
team4343/MaxXI pull request #8
Opened 2023-02-18 01:30 UTC by Vortex148

Added intake command and added states to intake subsystem

2023-02-18 19:13 UTC, bobbbay requested changes
Otherwise, LGTM, has it been tested yet?

2023-02-18 19:13 UTC, bobbbay commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    private final Intake_Speed Stopped = new Intake_Speed(0);
What are you trying to do here? If you're trying to have a set of constant intake speeds, put it in RPMs in `Constants.java`.

2023-02-18 20:57 UTC, Vortex148 commented
Has not been tested yet

2023-03-07 00:22 UTC, AlexanderDefuria approved these changes

2023-03-07 00:23 UTC, merged